openapi: 3.0.0
info:
  title: Заказ ресурсов на облаке
  description: OPEN API для заказа ресурсов на облаке
  version: 0.0.1
servers:
  - url: http://localhost:8080/api/v1
paths:
  /user:
    post:
      summary: Метод логина/регистрации пользователя
      tags:
        - User
      operationId: userAuthorization
      requestBody:
        content:
          adplication/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        "200":
          description: Ответ с id пользователя
          content:
            adplication/json:
              schema:
                $ref: "#/components/schemas/User"
        "default":
          description: Все остальное
          content:
            adplication/json:
              schema:
                $ref: "#/components/schemas/Error"
  
  /clouds:
    get:
      summary: Метод получения списка ресурсов
      tags:
        - Clouds
      operationId: getAllClouds
      responses:
        "200":
          description: Успешный ответ со списком ресурсов
          content:
            adplication/json:
              schema:
                $ref: "#/components/schemas/Clouds"
        "default":
          description: Все остальное
          content:
            adplication/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    User:
      type: object
      required:
        - user_id
        - name
        - email
        - password_hash
      properties:
        user_id:
          type: integer
          example: 1
        name:
          type: string
          example: "NoName"
        email:
          type: string
          example: "noname@gmail.com"
        password_hash:
          type: string
          example: "ajfdsfdgagsfsfsfsvvvvbhv"
    Cloud:
      type: object
      required:
        - id_client
        - OS
        - RAM
        - CPU
        - HDD
        - start_date
        - end_date
        - ip
      properties:
        cloud_id:
          type: integer
          example: 1
        id_client:
          type: integer
          example: 1
        OS:
          type: string
          enum:
            - Windows
            - Linux
          description: Орерационная система
        RAM:
          type: integer
          example: 256
        CPU:
          type: integer
          example: 12
        HDD:
          type: integer
          example: 1024
        start_date:
          type: string
        end_date:
          type: string
        ip:
          type: string
    Clouds:
      type: array
      items:
        $ref: "#/components/schemas/Cloud"
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
        message:
          type: string
          
        